name: inquiry_debug_auto_respond
enabled: true

trigger:
  type: core.st2.generic.inquiry

criteria:
  trigger.route:
    type: regex
    pattern: "[0-9a-f]+"

action:
  ref: examples2.inquiry_debug_respond
  parameters:
    inquiry_id: "{{ trigger.id }}"
    root_execution_id: "{{ trigger.route }}"
